# Generated by Django 3.0.3 on 2020-02-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.IntegerField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
                ('toppings_ids_json', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('pizzas_ids_json', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
