# Generated by Django 3.0.3 on 2020-02-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pizzavotes_toppingvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzavotes',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='toppingvotes',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
