# Generated by Django 3.0.3 on 2020-02-24 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200223_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=40, null=True)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
